# Generated by Django 5.1.4 on 2024-12-12 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35)),
                ('endereco', models.CharField(max_length=50)),
                ('contato', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('data_criacao', models.DateTimeField(auto_created=True)),
                ('nome', models.CharField(max_length=65)),
                ('codigo', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=500, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidade_estoque', models.IntegerField()),
                ('categorias', models.ManyToManyField(related_name='produtos', to='atv.categoria')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='atv.fornecedor')),
            ],
        ),
    ]
