# Generated by Django 5.1.4 on 2024-12-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('data_criacao', models.DateTimeField(auto_created=True)),
                ('nome_produto', models.CharField(max_length=65)),
                ('codigo_produto', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=500, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidade_estoque', models.IntegerField()),
            ],
        ),
    ]
