# Generated by Django 5.1.4 on 2025-02-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='imagem',
            field=models.ImageField(default=None, null=True, upload_to='media/images'),
        ),
    ]
