# Generated by Django 5.1.4 on 2025-02-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atv', '0002_products_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='imagem',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
    ]
