# Generated by Django 5.1.4 on 2025-02-19 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atv', '0003_alter_products_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
